# Aliases for bash terminal

alias install='sudo pacman -S'
alias aur='yaourt -S'
alias emacs='emacs -nw'
alias edit='emacs'
alias x='startxfce4'
alias sd='sudo shutdown now'
alias rb='systemctl reboot'
alias snpm='sudo npm'
alias ls='ls --color=auto'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias chrome='google-chrome-stable'
alias google='lynx-google'
alias reload='source ~/.bashrc'
alias netflix='google-chrome-stable netflix.com'